title: Abhishek Patil # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computational Neuroscientist in Making 
  <br><br>
  PhD student at Vellore Institite of Technology, Vellore, India. 
  <br><br>
  Research: Creativity, Creative Aging, Neuroscience, Neurofeedback.
  <br><br>
  <a href="https://in.linkedin.com/in/abhishek-patil-421a8014b">View My LinkedIn Profile</a> 
  <br>
  <a href=https://twitter.com/PatilAbhishek32>Follow me on Twitter</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
