title: Abhishek Patil
 logo: "/images/logo1.png"
 description: > # your text below (remove <br> elements if you don't need line breaks)
   Computational Neuroscientist in making
  <br>
  
  PhD student at <a href="https://vit.ac.in" target="_blank" >VIT Vellore</a> in collaboration with Dr. Chih-Mao Huang and Dr. Hsu-Wen Huang <a href="https://huangslab.weebly.com" target="_blank" >HUANGS' lab</a>  
  
  <br><br>
  
  Research: Creativity, Creative Aging, Neuroscience, Neurofeedback.
  
  <br><br>
  
  <a href="https://in.linkedin.com/in/abhishek-patil-421a8014b" target="_blank" >View My LinkedIn Profile</a> 
  
  <br>
  
  <a href="https://twitter.com/PatilAbhishek32" target="_blank" >Follow me on Twitter</a> 
theme: jekyll-theme-minimal
