 title : <p align="center">Abhishek Patil</p>
 logo :  "/images/logo1.png"
 description : > # your text below (remove <br> elements if you don't need line breaks)
   <p align="center"> Computational Neuroscientist in making </p>
     
     PhD student at <a href="http://vit.ac.in/" target="_blank" >VIT, Vellore</a> in collaboration with Dr. Chih-Mao Huang and Hsu-Wen Huang <a href="https://huangslab.weebly.com" target="_blank" >HUANGS lab</a> 
     <br>
     Research Interests: Creativity, Creative Aging, Neuroscience, Neurofeedback
     
     <br><br><br><br><br><br>
     
     <a href="https://in.linkedin.com/in/abhishek-patil-421a8014b" target="_blank" >View My LinkedIn Profile</a> 
     <br>
     <a href="https://twitter.com/PatilAbhishek32" target="_blank" >Follow me on Twitter</a>
     <br>
     <a href="https://www.facebook.com/abhishek.patil.353803/" target="_blank" >Add me on Facebook</a>
     <br><br>

 theme : jekyll-theme-minimal
